services:
  cadmous:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - cadmous-data:/app/data
      - cadmous-media:/app/media
    env_file:
      - .env
    restart: unless-stopped

volumes:
  cadmous-data:
  cadmous-media:
